production:
  adapter: postgresql
  encoding: UTF8
  database: fmi_db_prod_evalcurs
  host: localhost
  pool: 5
  port: 5432
  username: fmi_user_evalcurs
  password: K3p0!3

development:
  adapter: postgresql
  encoding: UTF8
  database: evalcurs_development
  pool: 5
  port: 5432
  username: 
  password: 

test:
  adapter: postgresql
  encoding: UTF8
  database: evaluari_test
  pool: 5
  port: 5432
  username: 
  password:
