# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Curs.create([
  { :nume => "Limbaje Formale si Automate Finite", :tip => "seminar", :profesor_id => 17, :specializare => nil, :an => 1 },
  { :nume => "Limbaje Formale si Automate Finite", :tip => "laboratory", :profesor_id => 17, :specializare => nil, :an => 1 },
  { :nume => "Programare Orientata pe Obiecte", :tip => "seminar", :profesor_id => 17, :specializare => nil, :an => 1 },
  { :nume => "Programare Orientata pe Obiecte", :tip => "laboratory", :profesor_id => 17, :specializare => nil, :an => 1 },
  { :nume => "Concepte geometrice in grafica pe calculator", :tip => "course", :profesor_id => 1, :specializare => nil, :an => 3 },
  { :nume => "Programare Orientata pe Obiecte", :tip => "course", :profesor_id => 2, :specializare => nil, :an => 3 },
  { :nume => "Programare Orientata pe Obiecte", :tip => "seminar", :profesor_id => 2, :specializare => nil, :an => 1 },
  { :nume => "Programare Orientata pe Obiecte", :tip => "laboratory", :profesor_id => 2, :specializare => nil, :an => 1 },
  { :nume => "Limbaje Formale si Automate Finite", :tip => "course", :profesor_id => 2, :specializare => nil, :an => 3 }
], :without_protection => true )



DataEvaluare.create([
  { :grupa_terminal => false, :data => "2013-04-21" },
  { :grupa_terminal => true, :data => "2013-04-21" }
], :without_protection => true )



EvaluareCompletata.create([
  { :evaluare_disponibila_id => 1, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 2, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 3, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 4, :incognito_user_token => "123457", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123460", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123461", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 6, :incognito_user_token => "123469", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 1, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 2, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 3, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 4, :incognito_user_token => "123457", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123460", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123461", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 6, :incognito_user_token => "123469", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 1, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 2, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 3, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 4, :incognito_user_token => "123457", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123460", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123461", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 6, :incognito_user_token => "123469", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 1, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 2, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 3, :incognito_user_token => "1234", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 4, :incognito_user_token => "123457", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123460", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 5, :incognito_user_token => "123461", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 6, :incognito_user_token => "123469", :timp => nil, :continut => {} },
  { :evaluare_disponibila_id => 1279, :incognito_user_token => "chgzc1Z9KDOmV56KKtvyFw==", :timp => nil, :continut => {} }
], :without_protection => true )



EvaluareDisponibila.create([
  { :curs_id => 195, :grupa_nume => 134, :formular_id => 15 },
  { :curs_id => 196, :grupa_nume => 134, :formular_id => 15 },
  { :curs_id => 197, :grupa_nume => 131, :formular_id => 15 },
  { :curs_id => 197, :grupa_nume => 132, :formular_id => 15 },
  { :curs_id => 197, :grupa_nume => 133, :formular_id => 15 },
  { :curs_id => 198, :grupa_nume => 131, :formular_id => 15 },
  { :curs_id => 198, :grupa_nume => 132, :formular_id => 15 },
  { :curs_id => 195, :grupa_nume => 131, :formular_id => 15 },
  { :curs_id => 195, :grupa_nume => 132, :formular_id => 15 },
  { :curs_id => 195, :grupa_nume => 133, :formular_id => 15 },
  { :curs_id => 196, :grupa_nume => 131, :formular_id => 15 },
  { :curs_id => 196, :grupa_nume => 132, :formular_id => 15 },
  { :curs_id => 196, :grupa_nume => 133, :formular_id => 15 },
  { :curs_id => 199, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 199, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 199, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 199, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 199, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 200, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 200, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 200, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 200, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 200, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 201, :grupa_nume => 134, :formular_id => 15 },
  { :curs_id => 202, :grupa_nume => 134, :formular_id => 15 },
  { :curs_id => 202, :grupa_nume => 133, :formular_id => 15 },
  { :curs_id => 203, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 203, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 203, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 203, :grupa_nume => 344, :formular_id => 15 },
  { :curs_id => 203, :grupa_nume => 344, :formular_id => 15 }
], :without_protection => true )



Formular.create([
  { :continut => nil },
  { :continut => "{\"chestionar\" : [\n    {\"label\" : \"text intre tagurile label\"},\n    {\"intrebare\": [ {\"enunt\": \"text intre tagurile enunt\"},\n                    {\"raspuns\": \"text intre tagurile raspuns\"},\n                    {\"raspuns\": \"text intre tagurile raspuns\"}\n                  ]\n    },\n    {\"intrebare\": [ {\"enunt\": \"text intre tagurile enunt\"},\n                    {\"raspuns\": \"text intre tagurile raspuns\"},\n                    {\"raspuns\": \"text intre tagurile raspuns\"}\n                  ]\n    },\n    {\"label\" : \"text intre tagurile label\"},\n    {\"intrebare\": [ {\"enunt\": \"text intre tagurile enunt\"}\n      \n                  ]\n    },\n    {\"intrebare\": [ {\"enunt\": \"text intre tagurile enunt\"}\n      \n                  ]\n    }\n  ]\n}" }
], :without_protection => true )



Grupa.create([
  { :nume => 334, :studenti => 5, :terminal => true },
  { :nume => 131, :studenti => 2, :terminal => false },
  { :nume => 132, :studenti => 2, :terminal => false },
  { :nume => 133, :studenti => 6, :terminal => false },
  { :nume => 134, :studenti => 5, :terminal => false },
  { :nume => 141, :studenti => 0, :terminal => false },
  { :nume => 142, :studenti => 0, :terminal => false },
  { :nume => 143, :studenti => 0, :terminal => false },
  { :nume => 144, :studenti => 0, :terminal => false },
  { :nume => 231, :studenti => 0, :terminal => false },
  { :nume => 232, :studenti => 0, :terminal => false },
  { :nume => 233, :studenti => 0, :terminal => false },
  { :nume => 234, :studenti => 0, :terminal => false },
  { :nume => 241, :studenti => 0, :terminal => false },
  { :nume => 242, :studenti => 0, :terminal => false },
  { :nume => 243, :studenti => 0, :terminal => false },
  { :nume => 244, :studenti => 0, :terminal => false },
  { :nume => 331, :studenti => 0, :terminal => true },
  { :nume => 332, :studenti => 0, :terminal => true },
  { :nume => 333, :studenti => 0, :terminal => true },
  { :nume => 341, :studenti => 0, :terminal => true },
  { :nume => 342, :studenti => 0, :terminal => true },
  { :nume => 343, :studenti => 0, :terminal => true },
  { :nume => 344, :studenti => 6, :terminal => true }
], :without_protection => true )



IncognitoUser.create([
  { :token => "3agqBoyZYAhclCerpdCmcA==", :grupa_nume => 334 },
  { :token => "gC+ohsjQ95tXOJMAiz2GLw==", :grupa_nume => 334 },
  { :token => "CBUnEJK99O/DWV/oauKfPg==", :grupa_nume => 334 },
  { :token => "UnJ9JV1V3w1h2yDOsIAaHw==", :grupa_nume => 334 },
  { :token => "XuV5S+ngfwhBeua6QZOdFg==", :grupa_nume => 334 },
  { :token => "96/m5YdN8QaX0XHbq1GTvw==", :grupa_nume => 131 },
  { :token => "m4/kw20kSUrPxn2ugrg2FQ==", :grupa_nume => 131 },
  { :token => "Ul+Tf5rGWls2jf8mTi7GHg==", :grupa_nume => 132 },
  { :token => "vQE0QVVpcGE5O4GQnp0oJA==", :grupa_nume => 132 },
  { :token => "6VqRpLBkaG1rglHKxyKrgA==", :grupa_nume => 133 },
  { :token => "GEQroIvfeC7DWPUW/mJAWQ==", :grupa_nume => 133 },
  { :token => "6wza9yBAog/EO0nSQMwDOQ==", :grupa_nume => 133 },
  { :token => "iPqn2cA1cUy+vTBenUpCtA==", :grupa_nume => 133 },
  { :token => "RVQCFx6Uutl2MNmFxUj5lA==", :grupa_nume => 133 },
  { :token => "ddxTnl4xLWxmLi1vLoSCkQ==", :grupa_nume => 133 },
  { :token => "MDHEIwAzYOG6YXnlcWtgGw==", :grupa_nume => 134 },
  { :token => "hloCoYTcQ4FEbz9nchkq4g==", :grupa_nume => 134 },
  { :token => "chgzc1Z9KDOmV56KKtvyFw==", :grupa_nume => 134 },
  { :token => "8cVCKkcC5osVcoMtUnMW/w==", :grupa_nume => 134 },
  { :token => "7h1qXgAs7HKPUem0li92gQ==", :grupa_nume => 134 },
  { :token => "7GzE8dV79Chw51Ndksk3RQ==", :grupa_nume => 344 },
  { :token => "/kOgsjJvXuaFEUivy6X/YQ==", :grupa_nume => 344 },
  { :token => "GwmFCxA02ZtSugR4Gle5LA==", :grupa_nume => 344 },
  { :token => "t2By50d0TFWBABEf1EoTTg==", :grupa_nume => 344 },
  { :token => "8rzWpsZdtap9kGr/SLF0AQ==", :grupa_nume => 344 },
  { :token => "QIBxb1a4hyk69VXgX5pjuQ==", :grupa_nume => 344 }
], :without_protection => true )



Profesor.create([
  { :nume => "Dragulici", :prenume => "Dumitru" },
  { :nume => "Stupariu", :prenume => "Mihai-Sorin" },
  { :nume => "Profesor1", :prenume => "Profesor1" }
], :without_protection => true )



SesiuneActiva.create([
  { :incognito_user_token => nil, :incepere_data => nil }
], :without_protection => true )


